version: "2"
services:
  db:
    image: eccube/postgres:9.2
    environment:
      - POSTGRES_USER=eccube_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=eccube_db
  eccube3:
    build:
      args:
        - DBTYPE=pgsql
    environment:
      - PGPASSWORD=password
      - POSTGRES_ENV_POSTGRES_PASSWORD=password
  codecept:
    build:
      args:
        - DBTYPE=pgsql
